"""add table jokes and users_jokes

Revision ID: 4b8c8a3e2c2f
Revises: 48dc212be5df
Create Date: 2024-08-17 14:04:20.440184

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b8c8a3e2c2f"
down_revision: Union[str, None] = "48dc212be5df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jokes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jokes")),
    )
    op.create_table(
        "users_jokes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("joke_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["joke_id"],
            ["jokes.id"],
            name=op.f("fk_users_jokes_joke_id_jokes"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_users_jokes_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users_jokes")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_jokes")
    op.drop_table("jokes")
    # ### end Alembic commands ###
